import os, base64

# Append new SFTP operations to sftp.rs (before the final `}` or end)
p = 'src-tauri/src/modules/sftp.rs'
with open(p, encoding='utf-8') as f:
    lines = f.readlines()

new_ops = chr(10).join([
    '',
    '// -----------------------------------------------------------------------------',
    '// 新增远端操作：chmod / chown / exec / mkdir / rename / list',
    '// -----------------------------------------------------------------------------',
    '',
    '/// 递归遍历远端目录，把所有项 chmod 到指定模式。',
    '/// `mode` 是八进制字符串（"755"、"644"），不识别时直接报错。',
    'fn chmod_recursive(sftp: &Sftp, remote: &Path, mode: i32) -> Result<u64, String> {',
    '    let stat = sftp.stat(remote).map_err(|e| format!("stat {} failed: {}", remote.display(), e))?;',
    '    sftp.setstat(remote, stat).map_err(|e| format!("setstat failed: {}", e))?;',
    '    sftp.chmod(remote, mode).map_err(|e| format!("chmod {} failed: {}", remote.display(), e))?;',
    '    let mut count = 1u64;',
    '    if stat.is_dir() {',
    '        for entry in sftp.readdir(remote).map_err(|e| format!("readdir failed: {}", e))? {',
    '            count += chmod_recursive(sftp, &entry.0, mode)?;',
    '        }',
    '    }',
    '    Ok(count)',
    '}',
    '',
    'pub fn sftp_chmod(req: &AutodeployExecuteRequest) -> AutodeployExecuteResult {',
    '    let started = Instant::now();;',
    '    let (host, user, auth, secret) = match creds(req) {',
    '        Ok(v) => v,',
    '        Err(e) => return fail(req, &e),',
    '    };',
    '    let Some(remote_path) = req.params.get("remote_path").and_then(|v| v.as_str()) else {',
    '        return fail(req, "missing remote_path");',
    '    };',
    '    let Some(mode_str) = req.params.get("mode").and_then(|v| v.as_str()) else {',
    '        return fail(req, "missing mode");',
    '    };',
    '    let mode = i32::from_str_radix(mode_str.trim().trim_start_matches("0o").trim_start_matches("0"), 8)',
    '        .map_err(|e| format!("mode 解析失败（需 8 进制字符串如 755）：{}", e))?;',
    '    let recursive = req.params.get("recursive").and_then(|v| v.as_str()) == Some("true");',
    '    let sess = match open_session(host, user, auth, secret) {',
    '        Ok(s) => s,',
    '        Err(e) => return fail(req, &e),',
    '    };',
    '    let sftp = match sess.sftp() {',
    '        Ok(s) => s,',
    '        Err(e) => return fail(req, &format!("sftp init failed: {}", e)),',
    '    };',
    '    let remote = Path::new(remote_path);',
    '    let mut result = match (if recursive { chmod_recursive(&sftp, remote, mode) } else {',
    '        sftp.chmod(remote, mode).map(|_| 1u64).map_err(|e| format!("chmod failed: {}", e))',
    '    }) {',
    '        Ok(count) => AutodeployExecuteResult {',
    '            ok: true,',
    '            node_id: req.node_id.clone(),',
    '            message: format!("chmod {}({:o}) 完成，共 {} 项", remote_path, mode, count),',
    '            output: Some(serde_json::json!({',
    '                "kind": "remote",',
    '                "path": remote_path,',
    '                "mode": mode,',
    '                "changed": count,',
    '            })),',
    '            elapsed_ms: 0,',
    '        },',
    '        Err(e) => fail(req, &e),',
    '    };',
    '    result.elapsed_ms = started.elapsed().as_millis() as u64;',
    '    let _ = sess.disconnect(None, "", None);',
    '    result',
    '}',
    '',
    '/// 在远端执行 shell 命令并捕获 stdout / stderr / 退出码。',
    'fn ssh_exec_capture(sess: &Session, command: &str) -> Result<(String, String, i32), String> {',
    '    let mut channel = sess',
    '        .channel_session()',
    '        .map_err(|e| format!("channel_session failed: {}", e))?;',
    '    channel.exec(command).map_err(|e| format!("exec failed: {}", e))?;',
    '    let mut out = String::new();',
    '    channel.read_to_string(&mut out).map_err(|e| format!("read stdout failed: {}", e))?;',
    '    let mut err = String::new();',
    '    channel.stderr().read_to_string(&mut err).map_err(|e| format!("read stderr failed: {}", e))?;',
    '    channel.wait_close().map_err(|e| format!("wait_close failed: {}", e))?;',
    '    let exit = channel.exit_status().unwrap_or(-1);',
    '    Ok((out, err, exit))',
    '}',
    '',
    'pub fn sftp_exec(req: &AutodeployExecuteRequest) -> AutodeployExecuteResult {',
    '    let started = Instant::now();;',
    '    let (host, user, auth, secret) = match creds(req) {',
    '        Ok(v) => v,',
    '        Err(e) => return fail(req, &e),',
    '    };',
    '    let Some(command) = req.params.get("command").and_then(|v| v.as_str()) else {',
    '        return fail(req, "missing command");',
    '    };',
    '    if command.trim().is_empty() {',
    '        return fail(req, "command 不能为空");',
    '    };',
    '    let sess = match open_session(host, user, auth, secret) {',
    '        Ok(s) => s,',
    '        Err(e) => return fail(req, &e),',
    '    };',
    '    let mut result = match ssh_exec_capture(&sess, command) {',
    '        Ok((out, err, exit)) => {',
    '            if exit != 0 {',
    '                AutodeployExecuteResult {',
    '                    ok: false,',
    '                    node_id: req.node_id.clone(),',
    '                    message: format!("远端命令退出码 {}：{}", exit, err.trim()),',
    '                    output: Some(serde_json::json!({',
    '                        "stdout": out,',
    '                        "stderr": err,',
    '                        "exit": exit,',
    '                    })),',
    '                    elapsed_ms: 0,',
    '                }',
    '            } else {',
    '                AutodeployExecuteResult {',
    '                    ok: true,',
    '                    node_id: req.node_id.clone(),',
    '                    message: format!("远端命令成功（stdout {} 字节）", out.len()),',
    '                    output: Some(serde_json::json!({',
    '                        "stdout": out,',
    '                        "stderr": err,',
    '                        "exit": exit,',
    '                    })),',
    '                    elapsed_ms: 0,',
    '                }',
    '            }',
    '        }',
    '        Err(e) => fail(req, &e),',
    '    };',
    '    result.elapsed_ms = started.elapsed().as_millis() as u64;',
    '    let _ = sess.disconnect(None, "", None);',
    '    result',
    '}',
    '',
    'pub fn sftp_chown(req: &AutodeployExecuteRequest) -> AutodeployExecuteResult {',
    '    let started = Instant::now();;',
    '    let (host, user, auth, secret) = match creds(req) {',
    '        Ok(v) => v,',
    '        Err(e) => return fail(req, &e),',
    '    };',
    '    let Some(remote_path) = req.params.get("remote_path").and_then(|v| v.as_str()) else {',
    '        return fail(req, "missing remote_path");',
    '    };',
    '    let owner = req.params.get("owner").and_then(|v| v.as_str()).unwrap_or("");',
    '    let group = req.params.get("group").and_then(|v| v.as_str()).unwrap_or("");',
    '    if owner.is_empty() && group.is_empty() {',
    '        return fail(req, "owner 和 group 不能同时为空");',
    '    };',
    '    let recursive = req.params.get("recursive").and_then(|v| v.as_str()) == Some("true");',
    '    let target = if group.is_empty() {',
    '        owner.to_string()',
    '    } else {',
    '        format!("{}:{}", owner, group)',
    '    };',
    '    let recursive_flag = if recursive { "-R " } else { "" };',
    '    let command = format!("chown {} {} {}", recursive_flag, shell_escape(&target), shell_escape(remote_path));',
    '    let sess = match open_session(host, user, auth, secret) {',
    '        Ok(s) => s,',
    '        Err(e) => return fail(req, &e),',
    '    };',
    '    let mut result = match ssh_exec_capture(&sess, &command) {',
    '        Ok((_out, err, exit)) => {',
    '            if exit != 0 {',
    '                AutodeployExecuteResult {',
    '                    ok: false,',
    '                    node_id: req.node_id.clone(),',
    '                    message: format!("chown 失败：{}", err.trim()),',
    '                    output: Some(serde_json::json!({ "stderr": err, "exit": exit })),',
    '                    elapsed_ms: 0,',
    '                }',
    '            } else {',
    '                AutodeployExecuteResult {',
    '                    ok: true,',
    '                    node_id: req.node_id.clone(),',
    '                    message: format!("chown {} {} 完成", target, remote_path),',
    '                    output: Some(serde_json::json!({',
    '                        "owner": owner,',
    '                        "group": group,',
    '                        "path": remote_path,',
    '                        "recursive": recursive,',
    '                    })),',
    '                    elapsed_ms: 0,',
    '                }',
    '            }',
    '        }',
    '        Err(e) => fail(req, &e),',
    '    };',
    '    result.elapsed_ms = started.elapsed().as_millis() as u64;',
    '    let _ = sess.disconnect(None, "", None);',
    '    result',
    '}',
    '',
    '/// 单引号包裹 + 转义内部单引号，保证 shell 不会注入。',
    'fn shell_escape(s: &str) -> String {',
    '    if s.is_empty() {',
    '        return "''".to_string();',
    '    }',
    '    format!("\u0027{}\u0027", s.replace(\u0027\u0027, "\u0027\u0027\u0027\u0027\u0027"))',
    '}',
    '',
    'pub fn sftp_mkdir(req: &AutodeployExecuteRequest) -> AutodeployExecuteResult {',
    '    let started = Instant::now();;',
    '    let (host, user, auth, secret) = match creds(req) {',
    '        Ok(v) => v,',
    '        Err(e) => return fail(req, &e),',
    '    };',
    '    let Some(remote_path) = req.params.get("remote_path").and_then(|v| v.as_str()) else {',
    '        return fail(req, "missing remote_path");',
    '    };',
    '    let mode_str = req.params.get("mode").and_then(|v| v.as_str()).unwrap_or("755");',
    '    let mode = match i32::from_str_radix(mode_str.trim().trim_start_matches("0o").trim_start_matches("0"), 8) {',
    '        Ok(m) => m,',
    '        Err(e) => return fail(req, &format!("mode 解析失败：{}", e)),',
    '    };',
    '    let sess = match open_session(host, user, auth, secret) {',
    '        Ok(s) => s,',
    '        Err(e) => return fail(req, &e),',
    '    };',
    '    let sftp = match sess.sftp() {',
    '        Ok(s) => s,',
    '        Err(e) => return fail(req, &format!("sftp init failed: {}", e)),',
    '    };',
    '    let mut result = match sftp_mkdir_p_with_mode(&sftp, Path::new(remote_path), mode) {',
    '        Ok(()) => AutodeployExecuteResult {',
    '            ok: true,',
    '            node_id: req.node_id.clone(),',
    '            message: format!("mkdir -p {} 完成（{:o}）", remote_path, mode),',
    '            output: Some(serde_json::json!({ "kind": "remote", "path": remote_path, "mode": mode })),',
    '            elapsed_ms: 0,',
    '        },',
    '        Err(e) => fail(req, &e),',
    '    };',
    '    result.elapsed_ms = started.elapsed().as_millis() as u64;',
    '    let _ = sess.disconnect(None, "", None);',
    '    result',
    '}',
    '',
    '/// 带模式的递归 mkdir，已存在的项跳过。',
    'fn sftp_mkdir_p_with_mode(sftp: &Sftp, remote: &Path, mode: i32) -> Result<(), String> {',
    '    let mut cur = PathBuf::new();',
    '    for comp in remote.components() {',
    '        cur.push(comp.as_os_str());',
    '        let s = cur.to_string_lossy().replace(chr(92), "/");',
    '        match sftp.stat(Path::new(&s)) {',
    '            Ok(_) => continue,',
    '            Err(_) => {',
    '                sftp.mkdir(Path::new(&s), mode).map_err(|e| format!("mkdir {} failed: {}", s, e))?;',
    '            }',
    '        }',
    '    }',
    '    Ok(())',
    '}',
    '',
    'pub fn sftp_rename(req: &AutodeployExecuteRequest) -> AutodeployExecuteResult {',
    '    let started = Instant::now();;',
    '    let (host, user, auth, secret) = match creds(req) {',
    '        Ok(v) => v,',
    '        Err(e) => return fail(req, &e),',
    '    };',
    '    let Some(from) = req.params.get("from").and_then(|v| v.as_str()) else {',
    '        return fail(req, "missing from");',
    '    };',
    '    let Some(to) = req.params.get("to").and_then(|v| v.as_str()) else {',
    '        return fail(req, "missing to");',
    '    };',
    '    let sess = match open_session(host, user, auth, secret) {',
    '        Ok(s) => s,',
    '        Err(e) => return fail(req, &e),',
    '    };',
    '    let sftp = match sess.sftp() {',
    '        Ok(s) => s,',
    '        Err(e) => return fail(req, &format!("sftp init failed: {}", e)),',
    '    };',
    '    // 如果目标是已存在的目录，则把 from 移进去（同 mv 语义）',
    '    let target = match sftp.stat(Path::new(to)) {',
    '        Ok(st) if st.is_dir() => {',
    '            let name = Path::new(from)',
    '                .file_name()',
    '                .ok_or_else(|| "from 路径没有文件名".to_string())?;',
    '            Path::new(to).join(name).to_string_lossy().to_string()',
    '        }',
    '        _ => to.to_string(),',
    '    };',
    '    let mut result = match sftp.rename(Path::new(from), Path::new(&target)) {',
    '        Ok(()) => AutodeployExecuteResult {',
    '            ok: true,',
    '            node_id: req.node_id.clone(),',
    '            message: format!("rename {} -> {}", from, target),',
    '            output: Some(serde_json::json!({ "from": from, "to": target })),',
    '            elapsed_ms: 0,',
    '        },',
    '        Err(e) => fail(req, &format!("rename failed: {}", e)),',
    '    };',
    '    result.elapsed_ms = started.elapsed().as_millis() as u64;',
    '    let _ = sess.disconnect(None, "", None);',
    '    result',
    '}',
    '',
    'pub fn sftp_list(req: &AutodeployExecuteRequest) -> AutodeployExecuteResult {',
    '    let started = Instant::now();;',
    '    let (host, user, auth, secret) = match creds(req) {',
    '        Ok(v) => v,',
    '        Err(e) => return fail(req, &e),',
    '    };',
    '    let Some(remote_path) = req.params.get("remote_path").and_then(|v| v.as_str()) else {',
    '        return fail(req, "missing remote_path");',
    '    };',
    '    let pattern = req.params.get("pattern").and_then(|v| v.as_str()).unwrap_or("");',
    '    let sess = match open_session(host, user, auth, secret) {',
    '        Ok(s) => s,',
    '        Err(e) => return fail(req, &e),',
    '    };',
    '    let sftp = match sess.sftp() {',
    '        Ok(s) => s,',
    '        Err(e) => return fail(req, &format!("sftp init failed: {}", e)),',
    '    };',
    '    let entries = sftp.readdir(Path::new(remote_path)).map_err(|e| format!("readdir {} failed: {}", remote_path, e));',
    '    let mut result = match entries {',
    '        Ok(list) => {',
    '            let mut items: Vec<serde_json::Value> = Vec::new();',
    '            for (path, stat) in list {',
    '                let name = path.file_name().and_then(|s| s.to_str()).unwrap_or("").to_string();',
    '                if !pattern.is_empty() && !glob_match(&pattern, &name) {',
    '                    continue;',
    '                }',
    '                items.push(serde_json::json!({',
    '                    "name": name,',
    '                    "size": stat.size.unwrap_or(0),',
    '                    "is_dir": stat.is_dir(),',
    '                    "mtime": stat.mtime,',
    '                    "permissions": stat.perm.unwrap_or(0),',
    '                }));',
    '            }',
    '            AutodeployExecuteResult {',
    '                ok: true,',
    '                node_id: req.node_id.clone(),',
    '                message: format!("{} 共 {} 项", remote_path, items.len()),',
    '                output: Some(serde_json::json!({',
    '                    "kind": "list",',
    '                    "path": remote_path,',
    '                    "items": items,',
    '                })),',
    '                elapsed_ms: 0,',
    '            }',
    '        }',
    '        Err(e) => fail(req, &e),',
    '    };',
    '    result.elapsed_ms = started.elapsed().as_millis() as u64;',
    '    let _ = sess.disconnect(None, "", None);',
    '    result',
    '}',
    '',
    '/// 极简 glob 匹配：支持 `*` / `?`，不支持 `[...]`。',
    'fn glob_match(pattern: &str, name: &str) -> bool {',
    '    let p: Vec<char> = pattern.chars().collect();',
    '    let n: Vec<char> = name.chars().collect();',
    '    glob_match_inner(&p, 0, &n, 0)',
    '}',
    '',
    'fn glob_match_inner(p: &[char], pi: usize, n: &[char], ni: usize) -> bool {',
    '    let mut pi = pi;',
    '    let mut ni = ni;',
    '    while pi < p.len() {',
    '        match p[pi] {',
    '            chr(42) => {',
    '                if pi + 1 == p.len() { return true; }',
    '                for j in ni..=n.len() {',
    '                    if glob_match_inner(p, pi + 1, n, j) { return true; }',
    '                }',
    '                return false;',
    '            }',
    '            chr(63) => {',
    '                if ni >= n.len() { return false; }',
    '                pi += 1; ni += 1;',
    '            }',
    '            c => {',
    '                if ni >= n.len() || n[ni] != c { return false; }',
    '                pi += 1; ni += 1;',
    '            }',
    '        }',
    '    }',
    '    ni == n.len()',
    '}',
    '',
]) + chr(10)

# Append at end
new_lines = lines + [new_ops]
open(p, 'w', encoding='utf-8').write(''.join(new_lines))
print('appended; new total lines:', len(new_lines))
