// 内置工作流模板
//
// 每个模板都以一个 start 节点开始（流程入口，画布有且仅有一个），
// 以 end 节点结束。所有非 start/end 节点必须挂在 start 出发
// 的路径上，否则加载后会被 validateWorkflow 标为孤立。
//
// 节点尺寸 168×56，节点中心间距 210（视觉间隔 ~42px），整体走画布左半边；
// 右侧 Inspector 占 288px，画布可用宽 ~870px，4-5 节点可并排成行，
// 用户加载模板就能看到完整流水线，不需要先平移画布。

import type { Workflow, WorkflowTemplate } from "../types";

const FRONTEND_PUBLISH: Workflow = {
  version: 1,
  name: "前端页面发布",
  nodes: [
    {
      id: "n_start",
      type: "start",
      x: 20,
      y: 80,
      params: {},
      status: "idle",
    },
    {
      id: "n_src",
      type: "local_dir",
      x: 230,
      y: 80,
      params: { path: "" },
      status: "idle",
    },
    {
      id: "n_zip",
      type: "compress",
      x: 440,
      y: 80,
      params: { output: "", level: "deflate" },
      status: "idle",
    },
    {
      id: "n_upload",
      type: "sftp_upload",
      x: 650,
      y: 80,
      params: {
        host: "",
        user: "",
        auth: "key",
        secret: "",
        remote_path: "/var/www/app",
      },
      status: "idle",
    },
    {
      id: "n_notify_ok",
      type: "notify",
      x: 860,
      y: 32,
      params: {
        title: "前端发布成功",
        body: "dist 已上传到 /var/www/app",
        level: "success",
      },
      status: "idle",
    },
    {
      id: "n_end",
      type: "end",
      x: 860,
      y: 128,
      params: {},
      status: "idle",
    },
  ],
  connections: [
    {
      id: "c_start",
      fromNode: "n_start",
      fromPort: 0,
      toNode: "n_src",
      toPort: 0,
    },
    { id: "c1", fromNode: "n_src", fromPort: 0, toNode: "n_zip", toPort: 0 },
    {
      id: "c2",
      fromNode: "n_zip",
      fromPort: 0,
      toNode: "n_upload",
      toPort: 0,
    },
    {
      id: "c3",
      fromNode: "n_upload",
      fromPort: 0,
      toNode: "n_notify_ok",
      toPort: 0,
    },
    {
      id: "c4",
      fromNode: "n_upload",
      fromPort: 0,
      toNode: "n_end",
      toPort: 0,
    },
  ],
};

const BACKEND_WAR_PUBLISH: Workflow = {
  version: 1,
  name: "后端 War 发布",
  nodes: [
    {
      id: "n_start",
      type: "start",
      x: 20,
      y: 80,
      params: {},
      status: "idle",
    },
    {
      id: "n_war",
      type: "local_file",
      x: 230,
      y: 80,
      params: { path: "" },
      status: "idle",
    },
    {
      id: "n_backup",
      type: "sftp_backup",
      x: 440,
      y: 80,
      params: {
        host: "",
        user: "",
        auth: "key",
        secret: "",
        remote_path: "/var/www/app",
        backup_dir: "/var/backups",
      },
      status: "idle",
    },
    {
      id: "n_delete",
      type: "sftp_delete",
      x: 650,
      y: 80,
      params: {
        host: "",
        user: "",
        auth: "key",
        secret: "",
        remote_path: "/var/www/app/old",
      },
      status: "idle",
    },
    {
      id: "n_upload",
      type: "sftp_upload",
      x: 860,
      y: 80,
      params: {
        host: "",
        user: "",
        auth: "key",
        secret: "",
        remote_path: "/var/www/app",
      },
      status: "idle",
    },
    {
      id: "n_branch",
      type: "if_status",
      x: 1070,
      y: 80,
      params: {},
      status: "idle",
    },
    {
      id: "n_notify_ok",
      type: "notify",
      x: 1280,
      y: 32,
      params: {
        title: "后端 War 发布成功",
        body: "war 已发布到生产环境",
        level: "success",
      },
      status: "idle",
    },
    {
      id: "n_notify_fail",
      type: "notify",
      x: 1280,
      y: 128,
      params: {
        title: "后端 War 发布失败",
        body: "请检查 SFTP 连接或文件路径",
        level: "error",
      },
      status: "idle",
    },
    {
      id: "n_end",
      type: "end",
      x: 1490,
      y: 80,
      params: {},
      status: "idle",
    },
  ],
  connections: [
    {
      id: "c_start",
      fromNode: "n_start",
      fromPort: 0,
      toNode: "n_war",
      toPort: 0,
    },
    {
      id: "c1",
      fromNode: "n_war",
      fromPort: 0,
      toNode: "n_backup",
      toPort: 0,
    },
    {
      id: "c2",
      fromNode: "n_backup",
      fromPort: 0,
      toNode: "n_delete",
      toPort: 0,
    },
    {
      id: "c3",
      fromNode: "n_delete",
      fromPort: 0,
      toNode: "n_upload",
      toPort: 0,
    },
    {
      id: "c4",
      fromNode: "n_upload",
      fromPort: 0,
      toNode: "n_branch",
      toPort: 0,
    },
    {
      id: "c5",
      fromNode: "n_branch",
      fromPort: 0,
      toNode: "n_notify_ok",
      toPort: 0,
    },
    {
      id: "c6",
      fromNode: "n_branch",
      fromPort: 1,
      toNode: "n_notify_fail",
      toPort: 0,
    },
    {
      id: "c7",
      fromNode: "n_branch",
      fromPort: 0,
      toNode: "n_end",
      toPort: 0,
    },
  ],
};

const ROBUST_PUBLISH: Workflow = {
  version: 1,
  name: "健壮发布（含重试）",
  nodes: [
    {
      id: "n_start",
      type: "start",
      x: 20,
      y: 80,
      params: {},
      status: "idle",
    },
    {
      id: "n_src",
      type: "local_dir",
      x: 230,
      y: 80,
      params: { path: "" },
      status: "idle",
    },
    {
      id: "n_zip",
      type: "compress",
      x: 440,
      y: 80,
      params: { output: "", level: "deflate" },
      status: "idle",
    },
    {
      id: "n_retry",
      type: "retry",
      x: 650,
      y: 80,
      params: { max_retries: "3", retry_delay: "5" },
      status: "idle",
    },
    {
      id: "n_upload",
      type: "sftp_upload",
      x: 860,
      y: 80,
      params: {
        host: "",
        user: "",
        auth: "key",
        secret: "",
        remote_path: "/var/www/app",
      },
      status: "idle",
    },
    {
      id: "n_notify_ok",
      type: "notify",
      x: 1070,
      y: 32,
      params: {
        title: "发布完成",
        body: "dist 已成功发布",
        level: "success",
      },
      status: "idle",
    },
    {
      id: "n_end",
      type: "end",
      x: 1070,
      y: 128,
      params: {},
      status: "idle",
    },
  ],
  connections: [
    {
      id: "c_start",
      fromNode: "n_start",
      fromPort: 0,
      toNode: "n_src",
      toPort: 0,
    },
    { id: "c1", fromNode: "n_src", fromPort: 0, toNode: "n_zip", toPort: 0 },
    {
      id: "c2",
      fromNode: "n_zip",
      fromPort: 0,
      toNode: "n_retry",
      toPort: 0,
    },
    {
      id: "c3",
      fromNode: "n_retry",
      fromPort: 0,
      toNode: "n_upload",
      toPort: 0,
    },
    {
      id: "c4",
      fromNode: "n_upload",
      fromPort: 0,
      toNode: "n_notify_ok",
      toPort: 0,
    },
    {
      id: "c5",
      fromNode: "n_upload",
      fromPort: 0,
      toNode: "n_end",
      toPort: 0,
    },
  ],
};

const REMOTE_WORKFLOW: Workflow = {
  version: 1,
  name: "远端会话操作",
  nodes: [
    { id: "n_start", type: "start", x: 20, y: 100, params: {}, status: "idle" },
    { id: "n_session", type: "ssh_session", x: 230, y: 100, params: { host: "", user: "", auth: "key", secret: "" }, status: "idle" },
    { id: "n_src", type: "local_file", x: 230, y: 220, params: { path: "" }, status: "idle" },
    { id: "n_upload", type: "sftp_upload", x: 440, y: 100, params: { host: "", user: "", auth: "key", secret: "", remote_path: "/var/tmp/release" }, status: "idle" },
    { id: "n_extract", type: "remote_extract", x: 650, y: 100, params: { source_path: "", output: "/var/www/app", format: "auto" }, status: "idle" },
    { id: "n_copy", type: "remote_copy", x: 860, y: 100, params: { source_path: "", target: "/var/www/app-backup" }, status: "idle" },
    { id: "n_move", type: "remote_move", x: 1070, y: 100, params: { source_path: "", target: "/var/www/app-current" }, status: "idle" },
    { id: "n_chmod", type: "remote_chmod", x: 1280, y: 100, params: { source_path: "", mode: "755", recursive: "true" }, status: "idle" },
    { id: "n_chown", type: "remote_chown", x: 1490, y: 100, params: { source_path: "", owner: "", group: "", recursive: "true" }, status: "idle" },
    { id: "n_end", type: "end", x: 1700, y: 100, params: {}, status: "idle" },
  ],
  connections: [
    { id: "c0", fromNode: "n_start", fromPort: 0, toNode: "n_session", toPort: 0 },
    { id: "c_src_start", fromNode: "n_start", fromPort: 0, toNode: "n_src", toPort: 0 },
    { id: "c1", fromNode: "n_session", fromPort: 0, toNode: "n_upload", toPort: 0 },
    { id: "c_src", fromNode: "n_src", fromPort: 0, toNode: "n_upload", toPort: 1 },
    { id: "c2", fromNode: "n_session", fromPort: 0, toNode: "n_extract", toPort: 0 },
    { id: "c3", fromNode: "n_upload", fromPort: 0, toNode: "n_extract", toPort: 1 },
    { id: "c4", fromNode: "n_session", fromPort: 0, toNode: "n_copy", toPort: 0 },
    { id: "c5", fromNode: "n_extract", fromPort: 0, toNode: "n_copy", toPort: 1 },
    { id: "c6", fromNode: "n_session", fromPort: 0, toNode: "n_move", toPort: 0 },
    { id: "c7", fromNode: "n_copy", fromPort: 0, toNode: "n_move", toPort: 1 },
    { id: "c8", fromNode: "n_session", fromPort: 0, toNode: "n_chmod", toPort: 0 },
    { id: "c9", fromNode: "n_move", fromPort: 0, toNode: "n_chmod", toPort: 1 },
    { id: "c10", fromNode: "n_session", fromPort: 0, toNode: "n_chown", toPort: 0 },
    { id: "c11", fromNode: "n_chmod", fromPort: 0, toNode: "n_chown", toPort: 1 },
    { id: "c12", fromNode: "n_chown", fromPort: 0, toNode: "n_end", toPort: 0 },
  ],
};

export const BUILTIN_TEMPLATES: WorkflowTemplate[] = [
  {
    id: "frontend-publish",
    name: "前端页面发布",
    description: "本地 dist → 压缩 → SFTP 上传 → 成功通知 → 结束",
    workflow: FRONTEND_PUBLISH,
  },
  {
    id: "backend-war-publish",
    name: "后端 War 发布",
    description:
      "war → 远端备份 → 删旧版本 → 上传 → 状态分支（成功 / 失败各发通知）",
    workflow: BACKEND_WAR_PUBLISH,
  },
  {
    id: "robust-publish",
    name: "健壮发布（含重试）",
    description: "dist → 压缩 → 重试节点 → SFTP 上传 → 通知 / 结束",
    workflow: ROBUST_PUBLISH,
  },
  {
    id: "remote-workflow",
    name: "远端会话操作",
    description: "一次 SSH 会话 → 上传 → 解压 → 复制 → 移动 → chmod → chown",
    workflow: REMOTE_WORKFLOW,
  },
];
